# Generated by Django 2.1rc1 on 2018-08-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('amount', models.IntegerField(blank=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
